# _config.yml for GitHub Pages

# Site settings
title: Janvier Iyakaremye
subtitle: Data Analyst Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  A portfolio showcasing data analysis projects in finance,
  demonstrating skills in Python, R, Excel, Power BI, and Tableau.
  Passionate about transforming data into actionable insights.

# GitHub Pages specific settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://janvierscode.github.io" # Update this with your GitHub Pages URL

# SEO and social media settings
author: Janvier Iyakaremye
twitter_username: 
github_username: janvierscode
linkedin_username: janvierscode
email: iyakaremyejanvier@gmail.com

# Site URLs
linkedin_url: https://www.linkedin.com/in/janvierscode/
github_url: https://github.com/Janvierscode

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - .htaccess

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Comments (if you want to add Disqus later)
# disqus:
#   shortname: your-disqus-shortname

# Google Analytics (add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X

# Social sharing
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      share: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      comments: false
      share: true
